name: push
on:
    push:
        branches:
            - master
            - dev

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Copy repository
              uses: actions/checkout@v2

            - name: Set up Docker Buildx
              id: buildx
              uses: docker/setup-buildx-action@v1

            - name: Build image
              id: docker_build
              uses: docker/build-push-action@v2
              with:
                context: ./
                file: ./Dockerfile
                push: false
                tags: nestjs-boilerplate:latest
