name: push
on:
    push:
        branches:
            - master
            - dev
        paths-ignore:
            - 'docs/**'
            - '.vscode/**'
            - '.idea/**'
            - '.commitlintrc.js'
            - '.czrc'
            - '.env.example'
            - '.eslintrc.js'
            - '.prettierignore'
            - '.prettierrc'
            - 'firebase.spec.json.example'
            - 'README.md'

jobs:
    build-source:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [12.x, 14.x]

        steps:
            - name: Copy repository
              uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install yarn
              run: npm i -g yarn

            - name: Install npm dependencies
              run: yarn

            - name: Lint code
              run: yarn lint

            # - name: Run tests # unavailable for tests at now
            # run: npm run test

            - name: Build source
              run: |
                  yarn build
                  ls -la ./dist
